name: Build esp-idf image + dockerc

on:
  push:
    tags: ['v*']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: write

    steps:
      - name: Checkout esp-idf
        uses: actions/checkout@v4
        with:
          repository: espressif/esp-idf
          ref: master
          submodules: recursive
          path: esp-idf

      - name: Show context (debug)
        run: |
          pwd
          ls -la esp-idf/tools/docker

      - name: Build image
        working-directory: esp-idf
        run: |
          docker build -t idf-custom:latest-esp32c3 \
            --build-arg IDF_CLONE_BRANCH_OR_TAG=master \
            --build-arg IDF_CLONE_SHALLOW=1 \
            --build-arg IDF_INSTALL_TARGETS=esp32c3 \
            tools/docker

      - name: Fetch dockerc
        run: |
          wget -q https://github.com/NilsIrl/dockerc/releases/download/v0.3.2/dockerc_aarch64
          chmod +x dockerc_aarch64

      - name: Compile to standalone binary
        run: ./dockerc_aarch64 --image docker-daemon:idf-custom:latest-esp32c3 --output idf-custom-esp32c3

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: idf-custom-esp32c3-arm64
          path: idf-custom-esp32c3

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
         tag_name: latest
         files: idf-custom-esp32c3
